version: '3.8'

services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./:/home/
    working_dir: /home/
    container_name: app
    depends_on:
      - db
    command: './mvnw spring-boot:run'
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"